# Generated by Django 4.2.14 on 2024-08-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0003_locationcategory_description_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="person",
            name="viewer_pers_nicknam_04dc21_idx",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="nickname",
            new_name="display_name",
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["display_name"], name="viewer_pers_display_42388e_idx"
            ),
        ),
    ]
