# Generated by Django 4.2.14 on 2024-08-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "viewer",
            "0005_remove_eventsimilarity_viewer_even_diff_va_d6965d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsimilarity",
            name="length_diff",
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventsimilarity",
            name="position_diff",
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
