# Generated by Django 4.2.14 on 2024-08-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0006_eventsimilarity_length_diff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedfile",
            name="earliest_timestamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="importedfile",
            name="latest_timestamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
