# Generated by Django 4.2.15 on 2024-09-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0008_remove_schemaorgclass_parent_schemaorgrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="detected_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
