# Generated by Django 4.2.15 on 2024-09-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0009_photo_detected_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedfile",
            name="activity",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
