# Generated by Django 4.2.21 on 2025-05-15 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0011_phototag"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteinteraction",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viewer.person",
            ),
        ),
    ]
