# Generated by Django 4.2.22 on 2025-08-17 23:09

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0013_userprofile_squashed_0014_auto_20250817_2302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="settings",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
