# Generated by Django 4.2.22 on 2025-08-18 14:29

from django.db import migrations, models

def copy_values_to_temp_table(apps, schema_editor):
	Day = apps.get_model('viewer', 'Day')
	DayTemp = apps.get_model('viewer', 'DayTemp')
	for day in Day.objects.all():
		temp = DayTemp(
			date = day.date,
			wake_time = day.wake_time,
			bed_time = day.bed_time,
			timezone_str = day.timezone_str,
			cached_heart = day.cached_heart,
			cached_sleep = day.cached_sleep,
			is_public_holiday = day.is_public_holiday,
			sunrise_time = day.sunrise_time,
			sunset_time = day.sunset_time)
		temp.save()

class Migration(migrations.Migration):
	dependencies = [
		("viewer", "0016_alter_calendartask_unique_together_autotag_user_and_more"),
	]

	operations = [
		migrations.CreateModel(
			name="DayTemp",
			fields=[
				("date", models.DateField(primary_key=True, serialize=False)),
				("wake_time", models.DateTimeField(blank=True, null=True)),
				("bed_time", models.DateTimeField(blank=True, null=True)),
				("timezone_str", models.CharField(default="UTC", max_length=32)),
				("cached_heart", models.TextField(blank=True, null=True)),
				("cached_sleep", models.TextField(blank=True, null=True)),
				("is_public_holiday", models.BooleanField(default=False)),
				("sunrise_time", models.DateTimeField(blank=True, null=True)),
				("sunset_time", models.DateTimeField(blank=True, null=True)),
			],
		),
		migrations.RunPython(copy_values_to_temp_table),
	]
