# Generated by Django 4.2.22 on 2025-08-18 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("viewer", "0018_recreatedaymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="day",
            unique_together={("user", "date")},
        ),
    ]
