# Generated by Django 4.2.24 on 2025-09-20 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("viewer", "0022_add_users_to_other_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="passenger",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TransitMethod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="", max_length=32)),
                ("comment", models.TextField(blank=True, null=True)),
                ("icon", models.SlugField(default="road", max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "person photo",
                "verbose_name_plural": "person photos",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="transit_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viewer.transitmethod",
            ),
        ),
    ]
