# Generated by Django 4.2.24 on 2025-09-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0023_event_passenger_transitmethod_event_transit_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="transit_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="viewer.transitmethod",
            ),
        ),
    ]
