# Generated by Django 4.2.24 on 2025-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0024_alter_event_transit_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="datareading",
            name="cached_location",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
