# Generated by Django 4.2.24 on 2025-10-28 23:52

from django.db import migrations, models
import viewer.functions.file_uploads


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0025_datareading_cached_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=viewer.functions.file_uploads.user_profile_image_upload_location,
            ),
        ),
    ]
