# Generated by Django 4.2.24 on 2025-10-29 23:06

import django.core.serializers.json
from django.db import migrations, models
import viewer.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0026_userprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dashboard",
            field=models.JSONField(
                default=viewer.models.user.create_new_dashboard,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
