# Generated by Django 4.2.26 on 2025-11-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0027_userprofile_dashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="height",
            field=models.IntegerField(null=True),
        ),
    ]
