from viewer.views.days import *
from viewer.views.events import *
from viewer.views.health import *
from viewer.views.landing_pages import *
from viewer.views.locations import *
from viewer.views.misc import *
from viewer.views.people import *
from viewer.views.photos import *
from viewer.views.tags import *
from viewer.views.months import *
from viewer.views.webhook import *
from viewer.views.years import *
from viewer.views.questionnaires import *
from viewer.views.rdf import *
from viewer.views.tiles import *
from viewer.views.users import *
